### ISSUE TITLE
Plug In Not Working

### ISSUE THREAD

**Issue by Queenenrd17** [slonopot/Museexmatch#1]
Hiya, When I try to add your plugin I get an error saying Exception has been Thrown By the Target of an invocation

**Comment by Solomag** [comment]
Same there!

**Comment by Solomag** [comment]
For Fix that error just place .dlls in plugin folder without creating another folder for plugin. 
Thats really important by the way... (On skins it doesnt matter).

**Comment by slonopot** [comment]
> For Fix that error just place .dlls in plugin folder without creating another folder for plugin. Thats really important by the way... (On skins it doesnt matter).

So it does work fine if you put the dll files straight in the Plugins folder, is that right?

**Comment by Solomag** [comment]
> > For Fix that error just place .dlls in plugin folder without creating another folder for plugin. Thats really important by the way... (On skins it doesnt matter).
> 
> So it does work fine if you put the dll files straight in the Plugins folder, is that right?

Yes, I preffer to manage everything by folders, thats why I got that error.
