### ISSUE TITLE
An error occurred during Museexmatch startup: 'System.Dynamic.ExpandoObject' does not contain a definition for 'body'

### ISSUE THREAD

**Issue by thepwrtank18** [slonopot/Museexmatch#3]
MusicBee fails to recognize the plugin after this error.

**Comment by slonopot** [comment]
Any network obstuctions like firewalls or proxies? Does https://apic.musixmatch.com/ws/1.1/ open for you? Should contain Cannot GET though.
Did you try updating it to the latest version?

**Comment by thepwrtank18** [comment]
The URL opens correctly. I have the latest version, downloaded it last night.

**Comment by slonopot** [comment]
Completely remove your userToken entry from beenius.conf and try enabling the plugin or restarting MusicBee entirely, this will create a new account for you.
