### ISSUE TITLE
New MusicBee plugin for LRCLIB's API search?

### ISSUE THREAD

**Issue by sveakul** [slonopot/Museexmatch#5]
Hi slonopot, any chance of creating a lyric searcher for LRCLIB.net?  It has an open-source public API with details here:  [https://lrclib.net/docs](url).

A chap at the AIMP player forum recently wrote and posted one for that player's lyrics searcher script structure and man it is FAST and gets an amazing amount of hits.  He found it had both static and synchronized DB abilities so wrote separate ones for both.  I'll bet you could combine them in one and make formats option-selectable like you did with Museexmatch.

I know you have the chops to handle this after Museexmatch and Beenius, could you please consider giving it a try?  Thanks!!

**Comment by slonopot** [comment]
I'll take a look and build it some time in the upcoming days/week. Latest MusicBee versions also provide access to the files themselves and it allows the plugins to pull unaltered metadata, maybe it'll be of some use.

**Comment by slonopot** [comment]
Yes, sure, if the plugin won't be able to get the file info, the received track title, artist and album will be used. Synced or not will also be configurable, that comes by default. As for hits, the service is using external providers as well, I believe it pulls info from more services than Genius and Musixmatch and maybe it'll be able to get more hits, we'll see when it's done

**Comment by slonopot** [comment]
As per API reference, there are two lookup options. The first one requires track title, artist, album and duration to be supplied for a match to be found, this will probably be used if a file is present. The second one is just a plain search, like in Musixmatch or Genius, this might become a default option for streams. I'll try to test it with streams so please share any that you use

I'm now also thinking I should move away from configuration files and folder requirements, there's a chance I'll figure this out first try and it will be available in LRCLIB plugin first and in the others later, we'll also see how will it go.
